name: 'GitHub semver release'
description: "GitHub Action to perform a GitHub semantic version release, along with an update to the major version tag"
inputs:
  default-bump:
    description: 'Default semver segment to bump'
    default: 'minor'
    required: false
runs:
  using: "composite"
  steps:
    - name: GitHub Tag Bump
      uses: anothrNick/github-tag-action@v1
      id: tag
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEFAULT_BUMP: ${{ inputs.default-bump }}
        RELEASE_BRANCHES: "main"
        DEFAULT_BRANCH: "main"
        WITH_V: "true"
        DRY_RUN: "true"
    - name: List Release
      if: steps.tag.outputs.part != 'none'
      run: echo "This will create the release '${{ steps.tag.outputs.new_tag }}'"
      shell: bash
    - name: Parse higher semantic versions
      id: semver
      if: steps.tag.outputs.part != 'none'
      shell: bash
      run: |
        TAG="${{ steps.tag.outputs.new_tag }}"
        MINOR="${TAG%.*}"
        MAJOR="${MINOR%.*}"
        echo "major=$(echo $MAJOR)" >> $GITHUB_OUTPUT
        echo "minor=$(echo $MINOR)" >> $GITHUB_OUTPUT
    # from https://github.com/google-github-actions/.github/blob/main/.github/workflows/release.yml
    # current version: https://github.com/google-github-actions/.github/blob/a569c9b05443b682e293700932a0db23ae21c344/.github/workflows/release.yml#L80
    - name: 'Update floating tag'
      uses: 'actions/github-script@v6'
      if: steps.tag.outputs.part != 'none'
      with:
        script: |-
          const sha = `${{ github.sha }}`;
          const major = `${{ steps.semver.outputs.major }}`;

          // Try to update the ref first. If that fails, it probably does not
          // exist yet, and we should create it.
          try {
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${major}`,
              sha: sha,
              force: true,
            });
            core.info(`Updated ${major} to ${sha}`);
          } catch(err) {
            core.warning(`Failed to create tag ${major}: ${err}`);
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${major}`,
              sha: sha,
            });
            core.info(`Created ${major} at ${sha}`);
          }
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.tag.outputs.part != 'none'
      with:
        body: ${{ github.event.head_commit.message }}
        tag: ${{ steps.tag.outputs.new_tag }}
        generateReleaseNotes: true
