name: Publish GitHub Action

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GitHub semver release
        uses: vivantehealth/github-semver-release-action@v0
        with:
          default-bump: patch
