name: Publish GitHub Action

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GitHub semver release
        uses: ./action.yml
        with:
          default-bump: patch
